encoding: "bom|utf-8"
title: Валянціна Жгарова - персанальная старонка
description: 'Персанальная старонка Валянціны Жгаровай'
keywords:
  - Валянціна Жгарова


baseurl: ""

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-93082706-1

sass:
    style: :compressed

compress_html:
  blanklines: true

excerpt_separator: <!--more-->

exclude:
  - _site
  - .git
  - Gemfile
  - Gemfile.lock
  - jekyll-server.cmd

permalink: /:title/

gems:
